### ISSUE TITLE
How to generate a graph with no weights

### ISSUE THREAD

**Issue by kgashok** [ufkapano/graphs-dict#6]
Is there a way to do this?

**Comment by ufkapano** [comment]
In the 'factory' module there are many generators for graphs with weights because it is useful for me. You can manually change the code and set all weights to 1 (create a new module 'factory_without_weights')
Generally, edges have default weight equal to 1.

--
dr hab. Andrzej Kapanowski
Sekretarz Wydziałowego Zespołu Rekrutacyjnego
Uniwersytet Jagielloński, Instytut Fizyki
30-384 Kraków, Łojasiewicza 11
tel. +48 12 664 4628
email: andrzej.kapanowski@uj.edu.pl

________________________________
Od: Ashok Bakthavathsalam <notifications@github.com>
Wysłane: poniedziałek, 10 lutego 2020 17:50
Do: ufkapano/graphs-dict <graphs-dict@noreply.github.com>
DW: Subscribed <subscribed@noreply.github.com>
Temat: [ufkapano/graphs-dict] How to generate a graph with no weights (#6)


Is there a way to do this?
